spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**

  jade4j:
    caching: false

  jpa:
    show-sql: ${hibernate.show-sql}
    hibernate:
      ddl-auto: ${hibernate.ddl-auto}
      format-sql: ${hibernate.format-sql}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db.hostname}:${db.port}/${db.schema}?createDatabaseIfNotExist=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:

    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: localhost
    port: 6379
    default_expire_time: 86400
info:
  component: This is REST API for Notarial Services.

server:
  port: 8080
  servlet:
    context-path:
logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG